global:
  scrape_interval: 5s
  external_labels:
    monitor: 'app-monitoring'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['advertising_prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['advertising_node_exporter:9100']

  - job_name: 'rest'
    metrics_path: '/v1/metrics'
    static_configs:
      - targets: ['advertising_nginx:80']
